# http://module-build.sourceforge.net/META-spec.html
name:         Sub-ScopeFinalizer
version:      0.02
version_from: lib/Sub/ScopeFinalizer.pm
installdirs:  site
author:       YAMASHINA Hio <hio@cpan.org>
abstract: execute a code on exiting scope.
license: perl
#requires:
no_index:
  directory:
    - inc
    - t
    - example
build_requires:
  Test::More: 0

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.04, EUMM-6.17.
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
